[project]
name = "actc-hw3"
version = "0.1.0"
description = "A K8s-like orchestrator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.128.0",
    "pyyaml>=6.0.3",
    "uvicorn>=0.40.0",
    "pytest>=7.4.0",
    "requests>=2.31.0",
]
